Files Commit
Krishnare/home-work-1 pull request #1
Opened 2019-03-27 08:30 UTC by Krishnare

2019-03-27 10:23 UTC, st-zelenin requested changes

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +  }
* `data` argument is not used anywhere
* this constructor has no sense - it can be removed

2019-03-27 10:23 UTC, st-zelenin commented on js/apicall.js
> +const url = `https://newsapi.org/v1/articles?source=bbc-news&apiKey=${apiKey}`;
it would be great if you will fetch the list of news sources instead of hard-coded `bbc-news`. see documentation [here](https://newsapi.org/docs/endpoints/sources)

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +        return response.json();
here you could use a shorter syntax:
``` js
.then(response => response.json())
```

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +    let globalData = {};
* there is no need to declare this variable - you can update lines 12-15 like the following:
``` js
.then(newsJson => instance.printResults(newsJson))
```
* the variable name is too abstract (please try to use less abstract names for variables, e.g. `newsJson/news/articles` in this case)

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +      })
see my comment for line 7 - you can pass `myJson` (a bad name for this argument) directly to `printResults`

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +    let elementId = document.getElementById('newsDetails');
please try to use `const` in cases when you do not re-assign a variable

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +    data.articles.map((value, index) => {
* please try not to use abstract names - in this case use `article` instead of `value`

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +      }
as far as I understand, you display `author` only for the first `article`.
are all `articles` have the same author? it is strange...

2019-03-27 10:23 UTC, st-zelenin commented on js/news.js
> +const instance = new fetchdata();
I do not see any benefit of `class` usage here..
you could use at least one of these:
* a useful constructor (that, for example, initializes some fields)
* class fields
* class decomposition - e.g. one special class that fetches and draws news sources, a class that fetches and renders articles, and, may be, a class that composes these two mentioned classes
* may be inheritance (`extend`) - for example, you could introduce a base class with method `fetch(url)` that returns a result in json format and handles fetch errors

2019-03-27 10:38 UTC, Krishnare commented on js/news.js
> +      }
Yes all articles has the same name

2019-03-27 10:52 UTC, Krishnare commented on js/news.js
> +        return response.json();
Done

2019-03-27 10:52 UTC, Krishnare commented on js/apicall.js
> +const url = `https://newsapi.org/v1/articles?source=bbc-news&apiKey=${apiKey}`;
Done

2019-03-27 10:52 UTC, Krishnare commented on js/news.js
> +    let globalData = {};
Done

2019-03-27 10:52 UTC, Krishnare commented on js/news.js
> +      })
Done

2019-03-27 10:53 UTC, Krishnare commented on js/news.js
> +    let elementId = document.getElementById('newsDetails');
Done

2019-03-27 10:55 UTC, Krishnare commented on js/news.js
> +    data.articles.map((value, index) => {
Done

2019-03-28 12:44 UTC, st-zelenin approved these changes

2019-03-28 12:44 UTC, st-zelenin commented on js/apicall.js
> +  "https://newsapi.org/v2/sources?apiKey=720c0314e8b2423eb7e1ffca5a1eeeb1";
remove hard-code: use `apiKey` variable

2019-03-28 12:44 UTC, st-zelenin commented on js/apicall.js
> +sourceSelectBox.onchange = function() {
use arrow function

2019-03-28 12:44 UTC, st-zelenin commented on js/apicall.js
> +  const newsCategory = this.value;
use handler's argument

2019-03-28 12:44 UTC, st-zelenin commented on js/news.js
> +    super(data);
`fetchdata` class doesn't have a constructore with argument `data`

2019-03-28 12:44 UTC, st-zelenin commented on js/news.js
> +  apiFetcher(url) {
`fetchdata` class was expected to be a generic base class that is responsible for fetching any data by `url` and return json. here you have a very specific `apiFetcher` method (a strange name for a method) that has specific logic related with `newsSource` instance

2019-03-28 12:44 UTC, st-zelenin commented on js/news.js
> +  articlesProvider(data) {
this is a class method - please name class methods like functions, e.g. `renderArticles` (`<action><description>` - something like that)

2019-03-28 12:44 UTC, st-zelenin commented on js/news.js
> +        uniqueVal = index === 0 ? `<h1>${article.author}</h1>` : "";
I still do not understand why you show `author` only for the first article

2019-03-28 13:40 UTC, merged